### ISSUE TITLE
Raqote feedback?

### ISSUE THREAD

**Issue by jrmuizel** [h416/elliptician#3]
I saw you recently ported to raqote from footile. Do you have any feedback on the raqote API compared to footile?

**Comment by h416** [comment]
raqote api is easier to use. Thanks.

Do you plan to speed up?
footile contains simd code.
I haven't compared performance though.

https://github.com/DougLau/footile/blob/master/src/imgbuf.rs
https://github.com/DougLau/footile/blob/master/src/rgba8.rs

**Comment by jrmuizel** [comment]
Good to hear. I have plans to speed things up further.
